### ISSUE TITLE
Customizing keyboard shortcuts

### ISSUE THREAD

**Issue by magnetik** [lidel/google-music-hotkeys#1]
Hi,

Using this addon on firefox, I would like to use the media key instead of some combo on my keyboard. 

Is this feasible ?

Thanks

**Comment by lidel** [comment]
Not yet! It will be possible as soon as Mozilla implements GUI for customizing key shortcuts :)
There is are tickets about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384 & https://bugzilla.mozilla.org/show_bug.cgi?id=1320332
(feel free to register at Bugzilla and vote for the issue).
When implemented, you will be able to change default shortcuts.

(under Chrome  shortcuts can be customized at `chrome://extensions/configureCommands`)

**Comment by magnetik** [comment]
I voted on bugzilla, thanks for the fast answer :)

**Comment by raulpopadineti** [comment]
Upvoted as well.

**Comment by lidel** [comment]
Good news,  this will land in Firefox 60: 

- [Bug 1421811 - Provide a way for an extension to update the shortcut for its command](
https://bugzilla.mozilla.org/show_bug.cgi?id=1421811)

It is just an API, so after it lands I need to add UI for changing shortcuts in Firefox
Probably with help of this example app and lib:
- https://github.com/mdn/webextensions-examples/tree/master/commands
- https://github.com/piroor/webextensions-lib-shortcut-customize-ui

**Comment by rcdailey** [comment]
Knowing our luck, Firefox 60 will land right about the same time Google replaces Google Play Music with this YouTube Remix crap

**Comment by rcdailey** [comment]
Firefox 60 [has been released](https://www.mozilla.org/en-US/firefox/60.0/releasenotes/)!

**Comment by lidel** [comment]
![tumblr_lj57gozvbh1qdjdp1o1_500](https://user-images.githubusercontent.com/157609/39959139-9cfef54e-560d-11e8-84e1-8f00d0ad1511.jpg)

**Comment by lidel** [comment]
Shortcut key customization landed in [v1.6.0](https://github.com/lidel/google-music-hotkeys/releases/tag/v1.6.0). Requires Firefox 60 or later.

## How To Customize Shortcuts in Firefox >=60

Right-click on Browser Action or _Preferences_
> ![Right-click on Browser Action](https://user-images.githubusercontent.com/157609/39958925-24e00498-560a-11e8-937e-45bc8fbf43eb.png)

Old school shortcuts can be now changed thanks to [webextensions-lib-shortcut-customize-ui](https://github.com/piroor/webextensions-lib-shortcut-customize-ui):
> ![screenshot with old school shortcuts](https://user-images.githubusercontent.com/157609/39966689-5b7e9dce-56b0-11e8-886c-a98c2c3fef0e.png)


A cool feature is that you can also use "media keys" without any modifiers:
> ![screenshot with media key](https://user-images.githubusercontent.com/157609/39966694-6abf5b02-56b0-11e8-9ad4-ec1cde02bc29.png)

**Comment by rcdailey** [comment]
Can these be configured to be global like in chrome?

**Comment by lidel** [comment]
No, Firefox does not provide API for that yet, but there is a ticket requesting it for which you can vote for:
- [Bug 1411795 - Add global keyboard shortcut support to commands API](https://bugzilla.mozilla.org/show_bug.cgi?id=1411795)

**Comment by rcdailey** [comment]
Oh boy. Looks like I'm with chrome for a little while longer.
