### ISSUE TITLE
Cant set Global scope

### ISSUE THREAD

**Issue by sIRO2** [lidel/google-music-hotkeys#10]
I can't establish "Global" at the customization shortcut page.
Its like the setup didn't apply.
I tried to execute Chrome as admin aswell with the same result.

Any help would be aprecieate.

**Comment by lidel** [comment]
@sIRO2 what operating system and browser versions are you running?

**Comment by lidel** [comment]
(assuming no longer an issue, feel free to reopen with additional info if still relevant)
