### ISSUE TITLE
Ctrl-<space> stopped working

### ISSUE THREAD

**Issue by cmharr** [lidel/google-music-hotkeys#11]
When I first started using the add-on I was able to use Ctrl-<space> to play/pause by typing "space" in the Key identifier box. However, that functionality appears to have gone missing. Now, when I type in "space" or a ' ' and move to the next box, my entry is wiped out. Please either let me know what I'm doing wrong, or see if there's a bug.
Thanks!

**Comment by lidel** [comment]
Hi, sorry for not getting to this earlier.  I assume you are using Firefox?

AFAIK <kbd>Ctrl</kbd>+<kbd>Space</kbd> works fine, I was able to set this:

> ![screenshot_22](https://user-images.githubusercontent.com/157609/44403578-22d52f80-a555-11e8-8866-39408bd70c42.png)


After you move away from field containing <kbd>Space</kbd> it will be converted to actual space (<kbd>&nbsp;</kbd>), so it will look like this:

>  ![screenshot_21](https://user-images.githubusercontent.com/157609/44403583-2668b680-a555-11e8-9dd6-5b8138a2d173.png)

.. but it is only a visual quirk of [shortcut-customize-ui](https://github.com/piroor/webextensions-lib-shortcut-customize-ui/) (library we use in Firefox),
pressing <kbd>Ctrl</kbd>+<kbd>Space</kbd> works as expected.

If it does not work, there is a high chance some other extension is using <kbd>Ctrl</kbd>+<kbd>Space</kbd> already. In my case it was [LanguageTool](https://addons.mozilla.org/en-US/firefox/addon/languagetool/) (i had to disable it and everything started working). 

Let me know if any of the above solved issue for you.

**Comment by cmharr** [comment]
Thank you! It took some hunting but I found the Ctrl-Space defined in a Gnome 3 shortcut and once I cleared that, the Google music hotkey worked.
