### ISSUE TITLE
"Right" shortcut value is not working properly for me

### ISSUE THREAD

**Issue by SynVisions** [lidel/google-music-hotkeys#13]
"Left" seems to work fine, but "Right" gets translated to "right" and then shows up as an error.

This is with FF 66.0 (64-bit), Google Music Hotkeys 1.6.0 on macOS.

![Screen Shot 2019-03-20 at 4 36 21 PM](https://user-images.githubusercontent.com/2769203/54725996-56e5f280-4b2e-11e9-8986-670a8a3b2917.png)

**Comment by lidel** [comment]
Thank you for reporting, fixed in v1.6.1, make sure to update!
