### ISSUE TITLE
Ability to use shortcuts globally

### ISSUE THREAD

**Issue by cybermike844** [lidel/google-music-hotkeys#4]
The ability to use the shortcuts while using other applications would be awesome, thanks for the app!

**Comment by lidel** [comment]
If you are using **Chromium**, it is possible right now:

1. Open `chrome://extensions/configureCommands`
2. Switch preferred shortcuts' scope to _Global_:
   > ![peek 2017-11-28 19-44](https://user-images.githubusercontent.com/157609/33337860-a03f29f6-d474-11e7-88b9-748739b20725.gif)
3. That is all. _Global_ shortcuts should work even when Chrome isn’t ‘in focus’. 
    Keep in mind that _Global_ shortcuts can interfere with regular desktop app shortcuts.

If you are using **Firefox**, it is not implemented yet, but should be possible at some point in future.  
See #1  for more details.

Ps. I've updated README to [include these instructions](https://github.com/lidel/google-music-hotkeys#how-to-customize-shortcuts). Thanks for the idea! 👍
