### ISSUE TITLE
Shortcut using numpad?

### ISSUE THREAD

**Issue by twinysam** [lidel/google-music-hotkeys#7]
This is a great little plugin, but I wish I could do Ctrl+Shift+8 (as well as the other functions) on the numpad as well (doesn't currently work). Is this possible?

**Comment by lidel** [comment]
Are you using Chrome? Try [this](https://github.com/lidel/google-music-hotkeys#how-to-customize-shortcuts).

If you are using Firefox, see https://github.com/lidel/google-music-hotkeys/issues/1

**Comment by twinysam** [comment]
I am on Firefox, I guess I could change the shortcuts then, which would be neat. But it's not exactly what I was trying to do, I want to use the existing shortcuts across the entire keyboard.

**Comment by lidel** [comment]
@twinysam v1.6.0 enables Firefox users to customize bindings.
I hope it is enough – I am afraid we can't do better than that with current APIs.
