### ISSUE TITLE
MediaPlayPause has second binding

### ISSUE THREAD

**Issue by randm-ch** [lidel/google-music-hotkeys#9]
I have set `MediaPlayPause` for `Toggle Playback` in the Addon Options. Works great, thanks! But the playback is also toggled when I hit the [^] key ([Swiss-German keyboard layout](https://en.wikipedia.org/wiki/QWERTZ#Switzerland_(German,_French,_Italian,_Romansh),_Liechtenstein,_Luxembourg), that's the key just left of Backspace). Can I disable this?

**Comment by lidel** [comment]
I don't think this is related to extension itself.

What operating system are you using?
It sounds like either OS or some other app running on it is  hijacking <kbd>^</kbd> key, or  your hardware keyboard  has function keys that get triggered somehow.

**Comment by randm-ch** [comment]
I'm on Linux. I have tested this with both Arch and Ubuntu. It has something to do with the keyboard itself because the problem only occurs when I use my external keyboard, but not the one built in the laptop. Very strange but this indeed doesn't seem to be an issue with the extension. Closed. Thank you!

**Comment by randm-ch** [comment]
@lidel I just tested this again on another laptop (Ubuntu with GNOME) with no external keyboard. I have set:

- `MediaPlayPause` -> `Toggle Playback`
- `MediaPrevTrack` -> `Previous Song`
- `MediaNextTrack` -> `Next Song`

<kbd>^</kbd> toggles Playback (when focus is not in an input field) on this machine, and so do <kbd>MediaPrevTrack</kbd> and <kbd>MediaNextTrack</kbd> (they don't skip to the next/previous song). So it's not *just* the external keyboard.

Any idea what I might be doing wrong? I have unassigned the media keys in the Keyboard settings (otherwise it doesn't work at all). No other media player is runing, or even installed. I have disabled all other FF addons. FF version is 60.0.2. Thanks!

**Comment by lidel** [comment]
@randm-ch  tough cookie!  :thinking: 

Are you running the latest version of extension (1.6.0) and unchecked modifiers like on screenshot below?

> ![](https://user-images.githubusercontent.com/157609/39966694-6abf5b02-56b0-11e8-9ad4-ec1cde02bc29.png)

If so, I guess we need to do step-by-step elimination.

First, let's make sure X11 is getting proper keyboard events:
1.  install and start `xev -event keyboard` tool in terminal 
1. move mouse/focus to its white window
1. press <kbd>^</kbd>
1. copy console output  and paste here 
1. repeat for <kbd>MediaPrevTrack</kbd> and <kbd>MediaNextTrack</kbd>

On my machine pressing and releasing <kbd>^</kbd> produces 2 events:

```
KeyPress event, serial 28, synthetic NO, window 0x2800001,
    root 0xe3, subw 0x0, time 625073729, (460,699), root:(2757,702),
    state 0x1, keycode 15 (keysym 0x5e, asciicircum), same_screen YES,
    XLookupString gives 1 bytes: (5e) "^"
    XmbLookupString gives 1 bytes: (5e) "^"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0xe3, subw 0x0, time 625073879, (460,699), root:(2757,702),
    state 0x1, keycode 15 (keysym 0x5e, asciicircum), same_screen YES,
    XLookupString gives 1 bytes: (5e) "^"
    XFilterEvent returns: False
```

<kbd>MediaPrevTrack</kbd> and <kbd>MediaNextTrack</kbd>  should produce similar events, but with key names  `XF86AudioPrev` and `XF86AudioNext`.

**Comment by randm-ch** [comment]
<kbd>^</kbd>

    KeyPress event, serial 34, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90604340, (98,95), root:(188,308),
        state 0x10, keycode 21 (keysym 0xfe52, dead_circumflex), same_screen YES,
        XLookupString gives 1 bytes: (5e) "^"
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: True

    KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90604660, (98,95), root:(188,308),
        state 0x10, keycode 21 (keysym 0xfe52, dead_circumflex), same_screen YES,
        XLookupString gives 1 bytes: (5e) "^"
        XFilterEvent returns: False

<kbd>MediaPlayPause</kbd>

    KeyPress event, serial 37, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90619108, (2567,1133), root:(2657,1346),
        state 0x10, keycode 172 (keysym 0x1008ff14, XF86AudioPlay), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: True
    
    KeyRelease event, serial 38, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90619196, (2567,1133), root:(2657,1346),
        state 0x10, keycode 172 (keysym 0x1008ff14, XF86AudioPlay), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

<kbd>MediaPrevTrack</kbd>

    KeyPress event, serial 38, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90620644, (2567,1133), root:(2657,1346),
        state 0x10, keycode 173 (keysym 0x1008ff16, XF86AudioPrev), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False
    
    KeyRelease event, serial 38, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90620772, (2567,1133), root:(2657,1346),
        state 0x10, keycode 173 (keysym 0x1008ff16, XF86AudioPrev), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

<kbd>MediaNextTrack</kbd>

    KeyPress event, serial 38, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90621756, (2567,1133), root:(2657,1346),
        state 0x10, keycode 171 (keysym 0x1008ff17, XF86AudioNext), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False
    
    KeyRelease event, serial 38, synthetic NO, window 0x3e00001,
        root 0x1a8, subw 0x0, time 90621868, (2567,1133), root:(2657,1346),
        state 0x10, keycode 171 (keysym 0x1008ff17, XF86AudioNext), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

Looks good, right? Extension version is 1.6.0. I'm running a GNOME 3.28.1 X11 session.

**Comment by lidel** [comment]
Ok, this part looks as expected, which means something is hijacking or miss-representing  <kbd>^</kbd> event after it is received by X11. 

Do you experience the same bug when you change keyboard layout to `English (US)` ?

**Comment by randm-ch** [comment]
@lidel <kbd>^</kbd> (<kbd>=</kbd> with `English (US)` layout) doesn't trigger play/pause, but <kbd>MediaPrevTrack</kbd> and <kbd>MediaNextTrack</kbd> still do...

**Comment by lidel** [comment]
Ok, sounds like something specific to Ubuntu/DE. Sadly I don't have Ubuntu on my hands, 
but perhaps below helps?
- https://wiki.ubuntu.com/Hotkeys/Troubleshooting
- https://askubuntu.com/a/72584

**Comment by randm-ch** [comment]
@lidel I'm back on Arch and the issue persists. So either it's GNOME related or I'm just really unlucky ;) But I think as long as noone else has the same issue it's not worth investigating and I can live with it. Thanks for your time!
